Name:           ros-melodic-cob-control
Version:        0.7.7
Release:        1%{?dist}
Summary:        ROS cob_control package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/cob_control
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-cob-base-controller-utils
Requires:       ros-melodic-cob-base-velocity-smoother
Requires:       ros-melodic-cob-cartesian-controller
Requires:       ros-melodic-cob-collision-velocity-filter
Requires:       ros-melodic-cob-control-mode-adapter
Requires:       ros-melodic-cob-control-msgs
Requires:       ros-melodic-cob-footprint-observer
Requires:       ros-melodic-cob-frame-tracker
Requires:       ros-melodic-cob-model-identifier
Requires:       ros-melodic-cob-obstacle-distance
Requires:       ros-melodic-cob-omni-drive-controller
Requires:       ros-melodic-cob-trajectory-controller
Requires:       ros-melodic-cob-tricycle-controller
Requires:       ros-melodic-cob-twist-controller
BuildRequires:  ros-melodic-catkin

%description
cob_control meta-package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Aug 06 2019 Felix Messmer <felixmessmer@gmail.com> - 0.7.7-1
- Autogenerated by Bloom

